In [1]:
import tensorflow as tf

tensor = tf.random.uniform((5, 4), minval=1, maxval=10)

print("Original Tensor:")
print(tensor)

mean_value = tf.reduce_mean(tensor)
print("\nMean:", mean_value.numpy())

max_value = tf.reduce_max(tensor)
print("Max:", max_value.numpy())

std_value = tf.math.reduce_std(tensor)
print("Standard Deviation:", std_value.numpy())

reshaped_tensor = tf.reshape(tensor, (4, 5))

print("\nReshaped Tensor (4, 5):")
print(reshaped_tensor)

Original Tensor:
tf.Tensor(
[[9.028994  1.1297148 6.3496027 3.6098173]
 [2.1557252 2.632562  1.0693308 1.4526979]
 [8.232706  2.7114906 7.160108  2.9184575]
 [4.847191  3.4899364 1.4598926 6.4750214]
 [3.4265375 2.4995618 9.24977   9.131387 ]], shape=(5, 4), dtype=float32)

Mean: 4.451525
Max: 9.24977
Standard Deviation: 2.7949305

Reshaped Tensor (4, 5):
tf.Tensor(
[[9.028994  1.1297148 6.3496027 3.6098173 2.1557252]
 [2.632562  1.0693308 1.4526979 8.232706  2.7114906]
 [7.160108  2.9184575 4.847191  3.4899364 1.4598926]
 [6.4750214 3.4265375 2.4995618 9.24977   9.131387 ]], shape=(4, 5), dtype=float32)
